// <auto-generated />
namespace LudogorieFood.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Correctnextandprevfieldsname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Correctnextandprevfieldsname));
        
        string IMigrationMetadata.Id
        {
            get { return "201603121343180_Correct next and prev fields name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
